### ISSUE TITLE
Edit this page link does not show page content

### ISSUE THREAD

**Issue by snim2** [dxw/playbook#1000]
This is likely the result of !973 but we've had a few reports of the `Edit this page` not showing the page content that the user wanted to edit.

**Comment by snim2** [comment]
```unsentRequest.js:41          GET https://api.github.com/repos/dxw/playbook/git/trees/main:product-management 404
```

I'm wondering whether fe9f2eb0e17b0d68c40aab965da97f118ce0c72d is the problem?

**Comment by snim2** [comment]
That URL that 404s:

https://api.github.com/repos/dxw/playbook/git/trees/main:product-management

should be (I think?):

https://api.github.com/repos/dxw/playbook/git/trees/main:src/product-management

**Comment by snim2** [comment]
So for the prod environment, it looks like:

```yaml
  - name: who-we-are
    label: Who we are
    label_singular: Who we are page
    folder: who-we-are
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Permalink, name: permalink, widget: hidden, default: /:path/:basename/ }
      - { label: Body, name: body, widget: markdown, required: true }
```

Maybe needed:

```yaml
...
    folder: src/who-we-are
```
